import React from 'react';
import Head from 'next/head';
import { ChakraProvider } from '@chakra-ui/react';
import type { AppProps } from 'next/app';

const MyApp: React.FC<AppProps> = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Joshua Semana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <ChakraProvider>
          <Component {...pageProps} />
        </ChakraProvider>
      </Head>
    </>
  );
};

export default MyApp;
